language: cpp
dist: xenial
compiler: g++
sudo: required

before_install:
  - sudo add-apt-repository ppa:beineri/opt-qt-5.12.3-xenial -y
  - sudo apt-get update

install:
  - sudo apt-get install qt512base qt512xmlpattern libgl1-mesa-dev build-essentials
  - source /opt/qt512/bin/qt512-env.sh


script:
  - /opt/qt512/bin/qmake PREFIX=/usr
  - make
  - dpkg -x ./app_1-1_amd64.deb . ; find .
  - curl --upload-file ./opt/bsqmu/bin/bsqmu https://transfer.sh/bsqmu-git-$(git rev-parse --short HEAD)
