language: cpp
dist: xenial
compiler: g++
sudo: required

before_install:
  - sudo add-apt-repository ppa:beineri/opt-qt-5.12.3-xenial -y
  - sudo apt-get update

install:
  - sudo apt-get install qt512base qt512xmlpatterns libgl1-mesa-dev
  - source /opt/qt512/bin/qt512-env.sh


script:
  - ls -lAh
  - /opt/qt512/bin/qmake PREFIX=/usr
  - make
  - ls -lAh
  - curl --upload-file ./bsqmu https://transfer.sh/bsqmu-$(git rev-parse --short HEAD)
