branches:
  only:
    - master

install:
  - set QTDIR=C:\Qt\5.12.2\mingw73_32
  - set PATH=%QTDIR%\bin;C:\Qt\Tools\mingw530_32\bin;%PATH%
build_script:
  - qmake bsqmu.pro
  - mingw32-make
after_build:
  - windeployqt release/bsqmu.exe
  - cmd: cp LICENSE release/LICENSE.txt"
  - rm release/*.o
  - rm release/*.cpp

artifacts:
  - path: Output\bsqmu-*.exe
  - path: release
    type: zip
