branches:
  only:
    - master

install:
  - set QTDIR=C:\Qt\5.11.3\mingw53_32
  - set PATH=%QTDIR%\bin;C:\Qt\Tools\mingw530_32\bin;%PATH%
build_script:
  - dir /adh /s
  - qmake bsqmu.pro
  - mingw32-make
after_build:
  - windeployqt release/bsqmu.exe
  - rm release/*.o
  - rm release/*.cpp
  - dir /adh /s

artifacts:
  - path: release
    type: zip
